server:
  port: 8090

spring:
  config:
    name: xfg-dev-tech-dubbo-consumer

dubbo:
  application:
    name: xfg-dev-tech-dubbo
    version: 1.0.0
  registry:
     address: zookeeper://127.0.0.1:2181
#    address: N/A
  protocol:
    name: dubbo
    port: 20881